version : "2.19.1"

services:
    mariadb:
        restart: always
        container_name: mariadb
        networks:
            - Inception
        build:
            context: ./maria-db/
            dockerfile: Dockerfile
        tty: true
        volumes:
            - wp-mysql:/var/lib/mysql
        env_file:
            - .env
    wordpress:
        restart: always
        container_name: wordpress
        networks:
            - Inception
        build:
            context: ./wordpress/
            dockerfile: Dockerfile
        tty: true
        volumes:
            - wp-volume:/var/www/html/
        depends_on:
            - mariadb
        env_file:
            - .env
    nignx:
        restart: always
        container_name: nginx
        networks:
            - Inception
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        ports:
            - 443:443
        tty: true
        volumes:
            - wp-volume:/var/www/html/
        depends_on:
            - wordpress
        env_file:
            - .env
networks:
    Inception:
        driver: bridge

volumes:
    wp-volume:
        driver: local    
        driver_opts:
            o: bind
            type: none
            device: /home/login/data/wp-data/
    wp-mysql:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/login/data/db-data/
